### ISSUE TITLE
about  ImportError: No module named models.nets  

### ISSUE THREAD

**Issue by puface** [timctho/VNect-tensorflow#1]
hi timctho 
 /run_demo_tf.sh but i got an error 
     File "demo_tf.py" . line 10, in <module>
     from models.nets import vnect_model_bn_folded as vnect_model 
 ImportError: No module named models.nets  
       i download the tensorflow model abd then save models/weights/vnect_tf  
my system：
    ubuntu 16.04 64bit gtx1080ti cuda-8.0 python2.7 opencv 3.3.0  
i don't know why .pls help me thanks

**Comment by devilwarz** [comment]
add the following lines to the code

`import sys
sys.path.append(<path to the model folder>`

This will fix the issue.

**Comment by puface** [comment]
hi devilwarz 
   thanks your help  i add one line code at demo_tf.py 
    import sys 
    sys.path.append('/models/weights/vnect_tf') 
   but i always got same error

**Comment by timctho** [comment]
@puface I think it's because I forgot to add a `__init__.py` file in `models`

**Comment by puface** [comment]
hi all . 
        i can run demo_tf_gl.py . the code working to well .  thanks 
      i got 28-29 fps/s in my compute by demo_tf_gl.py

**Comment by HonglianJiang** [comment]
@puface  How do you solve this issue? I have the same issue~

**Comment by monajalal** [comment]
@puface  where did you download the VCNet tf model from? can you please share the link?
