### ISSUE TITLE
Issue Webcam heatmaps

### ISSUE THREAD

**Issue by moombasa** [timctho/VNect-tensorflow#15]
Hey,

I've been trying out this project and managed to get the demo working for pictures without any issues, however if I try to run the demo with a webcam instead of a picture I get weird results. 

No matter what is the font or if there's a subject in the frame, I get false heatmap (garbage) all over the picture. Did anyone manage to work with a video feed from a camera or is it a known issue? I compared the code of the image and video demo and they are both pretty much identical treatment wise.

I added a picture just to show what I mean by garbage, this is not static it changes at each iteration.

![heatmapissue](https://user-images.githubusercontent.com/19293455/42910193-91c5d414-8ab4-11e8-8111-11fc4728f726.png)

**Comment by Echo-08-lj** [comment]
hey
I have the same problem as you.How did you solve it？
