### ISSUE TITLE
How to properly run ? 

### ISSUE THREAD

**Issue by DanAmador** [timctho/VNect-tensorflow#18]
I find that the documentation is lacking and haven't really been able to run it. 

I've done the following

- Contact and get the author to send me the model and weights in the caffemodel format
- Convert it to a pickle format using [caffe_weights_to_pickle.py](https://github.com/timctho/VNect-tensorflow/blob/master/caffe_weights_to_pickle.py)
- Create an event file running the [model](https://github.com/timctho/VNect-tensorflow/blob/master/models/vnect_model.py) file and renamed it vnect_tf and saved it in the weights folder

Yet I can't run any of the demos, I'm getting a dataLoss error, more specifically:

`DataLossError (see above for traceback): Unable to open table file models/weights/vnect_tf: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?`

Is there something I need to do beforehand or did I do something wrong? I'd be willing to update the readme  or even create a script to automate the process if I get this running.

**Comment by Robinchacko** [comment]
https://github.com/timctho/VNect-tensorflow/issues/11#issuecomment-425325746
