### ISSUE TITLE
Real time estimation

### ISSUE THREAD

**Issue by oguzhankarabulut** [timctho/VNect-tensorflow#2]
It is amazing project! Thanks for sharing!

I want to ask is it  good for real time pose detection?

**Comment by timctho** [comment]
Yes, it is real time if you have a GTX1060 level gpu.

**Comment by oguzhankarabulut** [comment]
Thx for your reply :)
Do i need high gpu just for train ?

**Comment by oguzhankarabulut** [comment]
Thank you sir!

Which code is for realtime?

**Comment by oguzhankarabulut** [comment]
Thank you sir!
