### ISSUE TITLE
What's the point of applying different scale values in demo.py?

### ISSUE THREAD

**Issue by XinArkh** [timctho/VNect-tensorflow#20]
Hi! I am a bit of confused while reading your admirable work that I can't catch the point of the following part in _demo.py_:
https://github.com/timctho/VNect-tensorflow/blob/9aa423e9c6bffbec401f5c3e55a4f43126c8c645/demo.py#L32-L33

The original code meets errors when running under two scale values. And I simply try deleting either of these two values in order to fix those errors, which successfully generates relatively good results, too.
I wonder the idea of applying two kinds of scale values in this work. Could you tell me the motivation and the advantages of this strategy? Thank you very much!

**Comment by Robinchacko** [comment]
If you have read the Vnect paper, authors have mentioned the image scale augmentation while training the CNN model(perhaps its done to increase the amount of dataset to train the robust CNN model with limited dataset ). Whereas the GitHub repository work also followed the same scheme in Tensorflow to train the model again. However, in your case, I think you use this model just to predict the pose and it doesn't require the use of scaling. You will be able to predict the pose accurately as the model is well trained. I hope this helps your doubt.

**Comment by XinArkh** [comment]
> If you have read the Vnect paper, authors have mentioned the image scale augmentation while training the CNN model(perhaps its done to increase the amount of dataset to train the robust CNN model with limited dataset ). Whereas the GitHub repository work also followed the same scheme in Tensorflow to train the model again. However, in your case, I think you use this model just to predict the pose and it doesn't require the use of scaling. You will be able to predict the pose accurately as the model is well trained. I hope this helps your doubt.

Yes I did find it in the paper afterwards! It makes sense with your explanation, thank you very much!
