### ISSUE TITLE
[RQ] Models for research. (Yes, only for it)

### ISSUE THREAD

**Issue by meruune** [timctho/VNect-tensorflow#30]

**Comment by bigface0202** [comment]
Hi,

I asked about the model to the Vnect's author two weeks ago.
Last week, I got the answer from author and he gave me the access code.
Let's try it again. I think it's better to send email from your institutional mail address, and provide details of your research group, and a link to your group webpage.

I hope you get the access code.

**Comment by AkayabeKimitsu** [comment]
No! & @bigface0202 
I sent email about year ago and second about month ago, as i wrote.

I cannot provide my organisation details, could it aint organsation.
I'm just normal person not havin webpage too, so what can i do?

Do i need to send them my work?
Do i need to create new email?
Do i need to bypass 501 code?

And last question.
You said they replied to you,
but you have organization? Webpage?

They said they send models only to researchers, but if i need to include website, addresses, my credit card and twitch password, is it still research?

Think about it man.
https://i.kym-cdn.com/entries/icons/mobile/000/022/138/highresrollsafe.jpg

Bye!~

**Comment by bigface0202** [comment]
Hmm..., I told them that I am PhD student and research about the human modeling.
Then, they asked my organization email address (is given by university or company), research detail, and web page of my laboratory.

Sorry I cannot help you anymore, if you cannot prove the researcher by using e-mail address or organization web page.
Good luck.

**Comment by AkayabeKimitsu** [comment]
So essentinal is to have organisation email address.
I understood,
Thanx!
