### ISSUE TITLE
about VNect-tensorflow models

### ISSUE THREAD

**Issue by puface** [timctho/VNect-tensorflow#4]
hi timctho 
      i test VNECT-tensorflow , i find Vnect-tf very faster but less accurate . i want to know about your tensorflow model come from . how i do train myself mode .?

**Comment by EJShim** [comment]
I've tested both .caffe and tf version of Vnect, and figured out there is a precision difference between caffe and tensorflow. You might be abled to amplify it, or just re-train using tf model

**Comment by Robinchacko** [comment]
@EJShim  I was trying to run demo.py file and I am getting an error like this...
```
Traceback` (most recent call last):
  File "demo.py", line 187, in <module>
    demo()
  File "demo.py", line 82, in demo
    cam_img = utils.read_square_image(img_path, '', args.input_size, 'IMAGE')
AttributeError: 'module' object has no attribute 'read_square_image'
```
Do you know  what is the reason?
Thanks
