### ISSUE TITLE
Where can I download the weights (vnect_tf)?

### ISSUE THREAD

**Issue by EJShim** [timctho/VNect-tensorflow#5]
Hello

Thank you for your implementation.

I am trying to run the demo, but getting errors because of the absence of model_file.

Is there anywhere that I can download the pre-trained weight file?

Thank you

**Comment by monajalal** [comment]
@EJShim  can you please share the model here or email it to jalal@bu.edu ? Thanks @timctho

**Comment by ruimgf** [comment]
I would like to get the model too. The autor send to me the original model in caffe implementation but i cannot convert this.
