### ISSUE TITLE
How to download the model?

### ISSUE THREAD

**Issue by HonglianJiang** [timctho/VNect-tensorflow#6]
could you attach the model?

**Comment by HonglianJiang** [comment]
@timctho when I try to run the ./run_demo_tf.sh, I got a error like "Failed to find any matching files for models/weights/vnect_tf", could you tell me how to download the file?

**Comment by timctho** [comment]
please send mail to me

**Comment by Robinchacko** [comment]
@HonglianJiang 
 Could you tel me How did you solved the problem?


>  when I try to run the ./run_demo_tf.sh, I got a error like "Failed to find any matching files for models/weights/vnect_tf", could you tell me how to download the file?
Thanks
