### ISSUE TITLE
Failed to find any matching files for models/weights/vnect_tf

### ISSUE THREAD

**Issue by yurinativo** [timctho/VNect-tensorflow#9]
Hi,

I couldn't run the demo becouse I don't have the vnect_tf.
Readme.md say: "1.Download model, put them in folder models/weights", but can not find the link to download.

Yuri
yurinativo@gmail.com

**Comment by sln45** [comment]
I contacted the author and received access to the file, but I still don't understand. The demo expects a file called vnect_tf with no extension, so presumably I need to do something with the university's caffemodel file before your program can use it. What am I missing?
